val appVersionName = project.findProperty("app.version.name")?.toString()
    ?: error("app.version.name is not defined in gradle.properties")
val appVersionCode = project.findProperty("app.version.code")?.toString()?.toIntOrNull()
    ?: error("app.version.code is not defined in gradle.properties")

val generateVersionFiles = tasks.register("generateVersionFiles") {
    group = "versioning"
    description = "Generates all version-derived files (xcconfig, WasmVersionInfo)"

    val xconfigFile = layout.projectDirectory.file("../iosApp/Configuration/Version.xcconfig").asFile
    val wasmOutputDir = layout.buildDirectory.dir("generated/source/version/wasmJsMain")

    inputs.property("versionName", appVersionName)
    inputs.property("versionCode", appVersionCode)
    outputs.file(xconfigFile)
    outputs.dir(wasmOutputDir)

    doLast {
        val name = inputs.properties["versionName"] as String
        val code = inputs.properties["versionCode"].toString()

        val xconfigContent =
            """
            // Generated by Gradle
            VERSION_NAME = $name
            VERSION_CODE = $code
            
            """.trimIndent()
        if (!xconfigFile.exists() || xconfigFile.readText() != xconfigContent) {
            xconfigFile.writeText(xconfigContent)
        }

        val wasmContent =
            """
            // Generated by Gradle
            package com.yasinkacmaz.jetflix.util

            internal object WasmVersionInfo {
                const val VERSION_NAME = "$name"
                const val VERSION_CODE = $code
            }
            """.trimIndent()
        val wasmFile = wasmOutputDir.get().asFile.resolve("com/yasinkacmaz/jetflix/util/WasmVersionInfo.kt")
        wasmFile.parentFile.mkdirs()
        if (!wasmFile.exists() || wasmFile.readText() != wasmContent) {
            wasmFile.writeText(wasmContent)
        }
    }
}

tasks.matching { it.name.startsWith("embedAndSign") }.configureEach {
    dependsOn(generateVersionFiles)
}

tasks.matching {
    (it.name.contains("Wasm") || it.name.contains("ktlint") || it.name.contains("Ktlint")) &&
        it.name != "generateVersionFiles"
}.configureEach {
    dependsOn(generateVersionFiles)
}

tasks.named("build") {
    dependsOn(generateVersionFiles)
}

tasks.named<Sync>("wasmJsBrowserDistribution") {
    inputs.property("versionName", appVersionName)
    doLast {
        val name = inputs.properties["versionName"] as String
        val versionFile = file("$destinationDir/version.txt")
        versionFile.writeText(name)
    }
    finalizedBy("wasmJsBrowserDistributionZip")
}

tasks.named<Sync>("wasmJsBrowserDevelopmentExecutableDistribution") {
    inputs.property("versionName", appVersionName)
    doLast {
        val name = inputs.properties["versionName"] as String
        val versionFile = file("$destinationDir/version.txt")
        versionFile.writeText(name)
    }
}

tasks.register<Zip>("wasmJsBrowserDistributionZip") {
    group = "distribution"
    description = "Zips Wasm distribution with version name"
    archiveFileName.set("jetflix-wasm-$appVersionName.zip")
    destinationDirectory.set(layout.buildDirectory.dir("dist/wasmJs/zip"))
    from(tasks.named("wasmJsBrowserDistribution"))
}
