#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4G

#Gradle
org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
android.enableJetifier=false

# App Versioning
app.version.name=4.0.0
app.version.code=6

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
