name: Build Release Apk And Bundle
on: workflow_dispatch
jobs:
  build-bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper
          cache-read-only: true
      - name: Copy Signing Properties
        run: |
          echo "${{ secrets.JETFLIX_KEYSTORE }}" > jetflix.keystore.asc
          gpg -d --passphrase "${{ secrets.JETFLIX_PASSPHRASE }}" --batch jetflix.keystore.asc > jetflix.keystore
          echo "${{ secrets.JETFLIX_SIGNING_PROPERTIES }}" > signing.properties.asc
          gpg -d --passphrase "${{ secrets.JETFLIX_PASSPHRASE }}" --batch signing.properties.asc > signing.properties
      - name: Build release apk and bundle
        run: ./gradlew assembleRelease bundleRelease
      - name: Share build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            app/build/outputs/apk
            app/build/outputs/bundle
