name: Build Release Apk And Bundle
on: workflow_dispatch
jobs:
  build-bundle:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Detect gradle version
        uses: actions/github-script@v7
        id: gradle-version-detector
        with:
          result-encoding: string
          script: |
            const scriptPath = '/./.github/scripts/gradle-version-detector.js'
            const script = require(`${process.env.GITHUB_WORKSPACE}${scriptPath}`)
            return script()
      - name: Fetch gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ steps.gradle-version-detector.outputs.result }}
      - name: Copy Signing Properties
        run: |
          echo "${{ secrets.JETFLIX_KEYSTORE }}" > jetflix.keystore.asc
          gpg -d --passphrase "${{ secrets.JETFLIX_PASSPHRASE }}" --batch jetflix.keystore.asc > jetflix.keystore
          echo "${{ secrets.JETFLIX_SIGNING_PROPERTIES }}" > signing.properties.asc
          gpg -d --passphrase "${{ secrets.JETFLIX_PASSPHRASE }}" --batch signing.properties.asc > signing.properties
      - name: Build release apk and bundle
        run: ./gradlew assembleRelease bundleRelease --no-configuration-cache
      - name: Share build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            app/build/outputs/apk
            app/build/outputs/bundle
