name: Tests
on:
  pull_request:
  workflow_dispatch:
jobs:
  tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Enable KVM group permissions for emulator hardware acceleration
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: 🔍 Detect Cache Key And Paths
        id: gradle-cache
        uses: actions/github-script@v7
        with:
          script: |
            const cacheDetectorScriptPath = '/./.github/scripts/gradle-cache-detector.js'
            const cacheDetectorScript = require(`${process.env.GITHUB_WORKSPACE}${cacheDetectorScriptPath}`)
            await cacheDetectorScript({core});
      - name: 🐘 Fetch gradle cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.gradle-cache.outputs['gradle-cache-paths'] }}
          key: ${{ steps.gradle-cache.outputs['gradle-cache-key'] }}
      - name: 🐘 Fetch build cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.gradle-cache.outputs['build-cache-paths'] }}
          key: ${{ steps.gradle-cache.outputs['build-cache-key'] }}
      - name: Run tests with xvfb
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 720x1280x24' ./gradlew --no-configuration-cache desktopTest --continue
      - name: Run tests
        continue-on-error: true
        run: ./gradlew --no-configuration-cache desktopTest --continue
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: Test Results
          junit_files: '**/test-results/**/*.xml'
